In [ ]:
import numpy as np
a=np.arange(1,13).reshape(2,6)#reshape(rows,columns)
print(a)#arrange(start,stop(inclusive),no of equal parts)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
a=np.linspace(1,12,12).reshape(2,6)#linspace is a bit different from range.Stop is exclusive in range but here it is inclusive
print(a)

[[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]


In [ ]:
b=np.array([1,2,3,4,5,6,7,8]).reshape(2,2,2)#reshape(group,row,column)
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#reshape returns the changed shape and resize reflects the change on the array just like sorted(l) and l.sort()
a=np.array([1,2,3,4])
print(a)
a.reshape(2,2)#returns the new array but no is storing it
print(a)
a.resize(2,2)#resize reflects the change to array
print(a)

[1 2 3 4]
[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
#adding arrays
a=np.array([1,2,3,4])#we cant perform arithmetic operations on two lists
b=np.array([1,2,3,4])
c=a+b
print(c)

[2 4 6 8]


In [ ]:
#arithmetic operations on arrays
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
c=b-a
d=a*b#one on one multiplication not matrix multiplication
e=a/b#one of one division
f=a@b#multiplication of matrix
g=a.dot(b)#multiplication of matrix through function
print(c)
print("---------------------")
print(d)
print("---------------------")
print(e)
print("---------------------")
print(f)
print("---------------------")
print("Array g:")
print(g)
print("---------------------")
print("maximum of array g:",g.max())
print("minimum of array g:",g.min())
print("maximum of every column in array g:",g.max(axis=0))#axis=0 is column wise. it prints required value in every column
print("minimum of every row in array g :",g.min(axis=1))#axis=1 is row wise. it prints required value in every row

[[4 4]
 [4 4]]
---------------------
[[ 5 12]
 [21 32]]
---------------------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
---------------------
[[19 22]
 [43 50]]
---------------------
Array g:
[[19 22]
 [43 50]]
---------------------
maximum of array g: 50
minimum of array g: 19
maximum of every column in array g: [43 50]
minimum of every row in array g : [19 43]


In [ ]:
#joining arrays!
a=np.array([1,2,3,4]).reshape(2,2)
b=np.array([5,6,7,8]).reshape(2,2)
print(a)
print("--------------")
print(b)
print("After vertical stacking")
print(np.vstack((a,b)))
print("After horizontal stacking")
print(np.hstack((a,b)))
print(np.stack((a,b),axis=0))#it is similar to vstack
print(np.stack((a,b),axis=1))#it is not hstack but joins nth row of 1st and 2nd array then n+1 row of 1st and 2nd array

[[1 2]
 [3 4]]
--------------
[[5 6]
 [7 8]]
After vertical stacking
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
After horizontal stacking
[[1 2 5 6]
 [3 4 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [ ]:
a=np.arange(30).reshape(2,3,5)
print(a)
print("\nafter dstack\n")#dimentionality stack
print(np.dstack(a))#no of rows--->no of groups
#no of columns in every group ---> no of rows in every group where ---> refers becomes

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

after dstack

[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
a=np.arange(18).reshape(6,3)
print(a)
print("After vertical splitting")
print(np.vsplit(a,3))#vsplit(array,no of parts)
print("After horizontal splitting")
print(np.hsplit(a,3))
print("non sequential vertical splitting")
print(np.vsplit(a,(2,3)))
print("non sequential horizontal splitting")
print(np.hsplit(a,[2]))#[] is used to split array into two non equal parts
#because if we give number there, it will think we are asking it to divide the array into n equal parts

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After vertical splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]
After horizontal splitting
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]
non sequential vertical splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]
non sequential horizontal splitting
[array([[ 0,  1],
       [ 3,  4],
       [ 6,  7],
       [ 9, 10],
       [12, 13],
       [15, 16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]


In [ ]:
A=np.array([17,21,32,56,43,72,69,100,23,101,5,1]).reshape(6,2)
print(A)
print(A.argmax())#returns index of max element in the array
print(A.argmin())#returns index of min element in the array
print(A.argmax(axis=0))#returns the index of max elements in every column
print(A.argmin(axis=0))#returns the index of min elements in every column
print(A.argmax(axis=1))#returns the index of max elements in every row
print(A.argmin(axis=1))#returns the index of min elements in every row

[[ 17  21]
 [ 32  56]
 [ 43  72]
 [ 69 100]
 [ 23 101]
 [  5   1]]
9
11
[3 4]
[5 5]
[1 1 1 1 1 0]
[0 0 0 0 0 1]


In [ ]:
a=np.array([12,34,25,66,71,88])
print("Mean :",np.mean(a))
print("Median :",np.median(a))
print("Variance :",np.var(a))
print("Standard deviation :",np.std(a))

Mean : 49.333333333333336
Median : 50.0
Variance : 743.888888888889
Standard deviation : 27.274326552435515


In [ ]:
#Trigonometry
A=np.pi
print("In radians :",A)#radiance
print("In degree :",np.rad2deg(A))#radiance to degree

In radians : 3.141592653589793
In degree : 180.0


In [ ]:
a=np.array([np.pi/4,np.pi/3,np.pi/2,np.pi])
print("In radians :",a)
print("In degree :",np.rad2deg(a))
print(a)

In radians : [0.78539816 1.04719755 1.57079633 3.14159265]
In degree : [ 45.  60.  90. 180.]
[0.78539816 1.04719755 1.57079633 3.14159265]


In [ ]:
c=np.array([0,30,45,60,90,120,180])
print(np.deg2rad(c))#degree to radiance

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [ ]:
print(np.sin(c))#printing sin values

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
 -0.80115264]


In [ ]:
print(np.cos(c))#printing cos values

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097
 -0.59846007]


In [ ]:
print(np.tan(c))#printing tan values

[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301
  1.33869021]


In [ ]:
print(np.arcsin(1))#sin^-1

1.5707963267948966


In [ ]:
print(np.arccos(1))#cos^-1

0.0


In [ ]:
print(np.arctan(1))#tan^-1

0.7853981633974483


In [ ]:
a=6
b=4
print(np.hypot(a,b))#Hypotenuse

7.211102550927978


In [ ]:
#searching in array
A=np.array([1,2,3,4,5,6,6,7,1])
print(np.where(A==1))

(array([0, 8]),)


In [ ]:
#searching even numbers in a array
print(np.where(A%2==0))

(array([1, 3, 5, 6]),)


In [ ]:
#searchsorted
a=np.array([3,45,21,34,90])
print(np.searchsorted(a,90))#returns the sorted position of element in the array
#sorted array is 3 21 34 45 90

4


Linear algebra and universal functions

In [ ]:
a=np.array([6,24,60,12,18])
b=np.array([6,4,10,5,4])
print(np.add(a,b))#same as a+b
print(a+b)
print(np.subtract(a,b))#same as a-b
print(a-b)
print(np.mod(a,b))#same as a%b
print(a%b)
print(np.divide(a,b))#same as a/b
print(a/b)
print(np.divmod(a,b))
print("Sorted array is :",np.sort(a))

[12 28 70 17 22]
[12 28 70 17 22]
[ 0 20 50  7 14]
[ 0 20 50  7 14]
[0 0 0 2 2]
[0 0 0 2 2]
[1.  6.  6.  2.4 4.5]
[1.  6.  6.  2.4 4.5]
(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))
Sorted array is : [ 6 12 18 24 60]


In [ ]:
a=np.array([6,12,34,56,9,10])
print(np.diff(a))#difference between adjacent two elements

[  6  22  22 -47   1]


set functions


In [ ]:
a=np.array([6,24,60,12,18])
b=np.array([6,4,10,5,4])
print(np.union1d(a,b))#a union b
print(np.setdiff1d(a,b))#difference
print(np.intersect1d(a,b))#intersection

[ 4  5  6 10 12 18 24 60]
[12 18 24 60]
[6]


Rounding

In [ ]:
a=np.trunc([-3.8547,3.5896])
print(a)
a=np.round([3.58,2.45])
print(a)
a=np.fix([3.5489,-5.489])
print(a)
a=np.around(3.16645,4)
print(a)
print(np.floor(3.45))
print(np.ceil(3.455))

[-3.  3.]
[4. 2.]
[ 3. -5.]
3.1665
3.0
4.0


More functions

In [ ]:
a=np.array([3,4,16,19,10])
print(np.cumsum(a))#cummulative sum
print(np.cumprod(a))#cummulative product
print(np.lcm(2,6))#lcm of 2 numbers
print(np.gcd(2,6))#gcd of 2 numbers
print(np.lcm.reduce(a))#to find lcm of array
print(np.gcd.reduce(a))#to find gcd of array

[ 3  7 23 42 52]
[    3    12   192  3648 36480]
6
2
4560
1


In [ ]:
a=np.array([[1,2],[3,4]])
print(np.linalg.inv(a))#inverse of matrix

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
from numpy import random as r
print(r.randint(20,50,size=6))#exclusive randint(start,stop,size=)
print(r.rand(20))#rand(no of values) limit between 0 and 1 but not 0 and 1

[20 39 44 34 47 27]
[0.24584914 0.96295678 0.31945092 0.05952882 0.11788586 0.38990539
 0.35852523 0.46179895 0.64028073 0.10046793 0.96100836 0.74512728
 0.1717186  0.44838275 0.89663552 0.65482999 0.14661473 0.91873273
 0.30762469 0.70107501]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.inner(a,b))#1x4+2x5+3x6=32
print(np.outer(a,b))#[1x[4,5,6] 2x[4,5,6] 3x[4,5,6]]
print(np.cross(a,b))#for 1st value leave 1st column and find ad-bc repeat this for remaining elements

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[-3  6 -3]
