In [ ]:
#printing a variable
a=10
print(a)

10


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#printing a variable with a string
a=10
print("a is:",a)

a is: 10


In [ ]:
#arithematic ops on two numbers
a=int(input("Enter a value:"))
b=int(input("Enter b value:"))
print("Sum is : ",a+b)
print("Difference is : ",a-b)
print("Product is : ",a*b)
print("Division is : ",a/b)
print("Exp is : ",a**b)
print("Remainder is : ",a%b)

Enter a value:13245
Enter b value:2
Sum is :  13247
Difference is :  13243
Product is :  26490
Division is :  6622.5
Exp is :  175430025
Remainder is :  1


In [ ]:
#Relation operators
#Take a number from the user, which is salary. If the salary is more than 50,000 there is a 10% tax deduction. print his final salary
a=int(input("Enter your salary : "))
if(a>=50000):
  print("Salary is : ",a-(a/10))
else:
  print("Salary is : ",a," which is less than 50000 so no tax deduction")

Enter your salary : 54123
Salary is :  48710.7


In [ ]:
#get the salary from the user, if the salary is more than or equal to 50000 apply 10% tax.
#If the salary is less than 50000 apply 5% tax, if the salary is more than 70000 apply 12% tax
#if salary exceeds one lakh print you are promoted.
a=int(input("Enter your salary : "))
if(a<50000):
  print("Salary is : ",a-(a/20))
elif(a<=70000):
  print("Salary is : ",a-(a/10))
elif(a<=100000):
  print("Salary is : ",a-(a*12/100))
else:
  print("You are promoted!")

Enter your salary : 100001
You are promoted!


In [ ]:
l=range(1,11)
print(list(l))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
#Multiplication table using for loop
n=int(input("Enter value : "))
for i in range(1,11):
  print(n,"x",i,"=",n*i)

Enter value : 100
100 x 1 = 100
100 x 2 = 200
100 x 3 = 300
100 x 4 = 400
100 x 5 = 500
100 x 6 = 600
100 x 7 = 700
100 x 8 = 800
100 x 9 = 900
100 x 10 = 1000


In [ ]:
#Multiplication table using While loop
n=int(input("Enter number:"))
i=1
while(i!=11):
  print(n,"x",i,"=",n*i)
  i+=1

Enter number:100
100 x 1 = 100
100 x 2 = 200
100 x 3 = 300
100 x 4 = 400
100 x 5 = 500
100 x 6 = 600
100 x 7 = 700
100 x 8 = 800
100 x 9 = 900
100 x 10 = 1000


In [ ]:
#list->heterogeneous
l=[1,2,3.4,"madhur",'A',True]
for i in l:
  print(i)

1
2
3.4
madhur
A
True


In [ ]:
#list mutable
l=[]
l.append(1)#listname.append(values)
l.append(1.5)
l.append("Madhur")
l.append(True)
l.insert(2,99)#listname.insert(index,value)
l1=[11,22,33]
l.extend(l1)#l=l+l1 listname.extend(list_to_be_added)
l.pop(-2)#listname.pop(index) -1 by default
l.remove(33)#listname.remove(value)
print(l)

[1, 1.5, 99, 'Madhur', True, 11]


In [ ]:
#clearing the list
l.clear()
print(l)

[]
[]


In [ ]:
#Create a list of random integers of 10 elements and print their squares save them in a new list
l=[11,24,38,42,59,61,75,86,93,100]#comprehension
#listname=[expression for_loop condition]
l1=[i*i for i in l]
print(l1)

[121, 576, 1444, 1764, 3481, 3721, 5625, 7396, 8649, 10000]


In [ ]:
l=[22,33,51,66,18]
res=[i if(i<50) else 'x' for i in l]#listname=[(statements of if) if(cond) else (statements of else) for(condition) ]
print(res)

[22, 33, 'x', 'x', 18]


In [ ]:
#Take the salary from user if it is less than 50K then apply 10% tax otherwise 15%
num=[100000,50000,25000,20000,75000]
l=[n-(n/10) if n<50000 else n-(n*15/100) for n in num]
print(l)

[85000.0, 42500.0, 22500.0, 18000.0, 63750.0]


In [ ]:
#Dictionary
#dict={key:value,key:value,key:value}
dict1={23:"Madhur",34:"Lokesh",35:"Venky",37:"Madhav",23:"Madhur Achanta"}#Same key exists then it will be overwritten
print(dict1)
print(dict1.keys())
print(dict1.values())
print(dict1[23])

{23: 'Madhur Achanta', 34: 'Lokesh', 35: 'Venky', 37: 'Madhav'}
dict_keys([23, 34, 35, 37])
dict_values(['Madhur Achanta', 'Lokesh', 'Venky', 'Madhav'])
Madhur Achanta


In [ ]:
dict3={'dept':"CSE",'details':{"year":2,'section':'D','count':71}}#nested dictionary
print(dict3['details']['section'])#accessing element in a nested dictionary
print(dict3['details'])

D
{'year': 2, 'section': 'D', 'count': 71}


In [ ]:
dict3={'dept':"CSE",'details':{"year":2,'section':'D','count':71}}#nested dictionary
print("Deparment : ",dict3["dept"])
print("Year : ",dict3["details"]["year"])
print("Section : ",dict3["details"]["section"])
print("Count :",dict3["details"]["count"])

Deparment :  CSE
Year :  2
Section :  D
Count : 71


In [ ]:
rollno=[1,2,3,4]
stu=["Madhur","Lokesh","Venky","Madhav"]
details=dict(zip(rollno,stu))
print(details)

{1: 'Madhur', 2: 'Lokesh', 3: 'Venky', 4: 'Madhav'}


In [ ]:
#numpy
import numpy as np
A=np.array([1,2,3,4]) #1D array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
B=np.array([[1,2,3,4],[5,6,7,8]])
print(B)
#Elements in the each row = columns
print("dimensions :",B.ndim)#no of dimensions
print("shape : ",B.shape)#rows columns

[[1 2 3 4]
 [5 6 7 8]]
dimensions : 2
shape :  (2, 4)


In [ ]:
c=np.array([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
print(c)
print("dimensions:",c.ndim)# no of dimensions
print("Shape:",c.shape)#groups rows columns

[[[1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]]]
dimensions: 3
Shape: (2, 2, 4)


In [ ]:
A=np.ones((2,3))#obj.ones((2,4,3))#2 groups 4 rows and 3 columns
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A=np.zeros((2,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a=np.eye(6)#identity matrix
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
a=np.arange(1,10,2)#similar to range function
print(a)

[1 3 5 7 9]


In [ ]:
#Print all the numbers that are divisible by 8 using arange function upto 1000
b=np.arange(8,1001,8)
print(b)

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]


In [ ]:
a=np.linspace(1,10,10)#splitting a range into n numbers with common differences.
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
